input:
  allowed_files:
  - .WAV
  - .wav
  - .mp3
  - .flac
  - .m4a
  limit_positives: 0
output:
  highpass_variable: 1000
  include_boxes: false # time-frequency bounding boxes
  include_kaytoo: false # coarse labels (soundfile?)
  include_coco_masks: false
  include_yolo_masks: false
  include_hrnet_masks: false # masks are 0 for background, 1, 2, 3... for classes (they look black in file viewer)
  include_unetplusplus_masks: true # very similar to hrnet masks but different structure and no lst files
  mask_threshold_db: 5
  log_scale_masks: true
  include_soundfile: false
  include_spectrogram: true
  length: 10
  lowpass_variable: 100
  n: 1000
  negative_overlay_range:
  - 0
  - 2
  overwrite_output_path: true
  positive_overlay_range:
  - 0
  - 5
  rainbow_frequency: false
  repetitions:
  - 1
  - 5
  single_class: true
  snr_range:
  - 0.9
  - 1
  val_ratio: 0.8
  concatenate: false
paths:
  hrnet_remote_dir: '/Users/kaspar/Library/CloudStorage/GoogleDrive-kaspar.kimutai@gmail.com/My Drive/Colab Notebooks/HRNet-Semantic-Segmentation/data' # this path is overwritten
  dataset: /Volumes/Rectangle/bioacoustic-data-augmentation-dataset
  do_train_val_split: false
  negative: negative
  noise: noise
  output: augmented_dataset_output # this path is overwritten every time main.py runs
  vocalisations: vocalisations
plot:
  color_filter: dusk
  toggle: true
  show_labels: true