input:
  allowed_files:
  - .WAV
  - .wav
  - .mp3
  - .flac
  - .m4a
  limit_positives: 0
output:
  highpass_variable: 0
  include_boxes: true
  include_kaytoo: true
  include_coco_masks: true
  include_yolo_masks: false
  mask_threshold_db: 15
  log_scale_masks: true
  include_soundfile: true
  include_spectrogram: true
  length: 10
  lowpass_variable: 0
  n: 3
  negative_overlay_range:
  - 0
  - 2
  overwrite_output_path: true
  positive_overlay_range:
  - 3
  - 3
  rainbow_frequency: false
  repetitions:
  - 3
  - 5
  single_class: false
  snr_range:
  - 0.9
  - 1
  val_ratio: 0.8
  concatenate: false
paths:
  dataset: /Volumes/Rectangle/bioacoustic-data-augmentation-dataset
  do_train_val_split: false
  negative: negative
  noise: noise
  output: augmented_dataset_output
  vocalisations: vocalisations
plot:
  color_filter: dusk
  toggle: true
  show_labels: false