paths:
  dataset: 'example_dataset'
  vocalisations: 'vocalisations'
  noise: 'noise'
  negative: 'negative'
  output: 'output'

# output data config
output:
  overwrite_output_path: True

  n: 3
  val_ratio: 0.8
  single_class: False
  include_soundfile: True
  # include_spectrogram: todo

  generate_masks: True

  positive_overlay_range: [0,5]
  # positive_overlay_range: [6,6]
  negative_overlay_range: [0,2]
  # negative_overlay_range: [2,2]
  repetitions: [1,10] # repetitions occur 50% of the time
  # repetitions: [0,0]

  # todo Logspec
  length: 10 # seconds
  rainbow_frequency: False # maybe helpful from https://www.sciencedirect.com/science/article/pii/S1574954121003253
  
plot:
  toggle: True
  color_filter: 'dusk' # 'dusk' # 'dusk' or None