input:
  allowed_files:
  - WAV
  - wav
  - mp3
  - flac
  limit_positives: 0
  labels_format: 'spreadsheet' ##### 'folders'
output:
  highpass_variable: 1000
  include_boxes: true # time-frequency bounding boxes
  include_kaytoo: true # coarse labels (soundfile?)
  include_coco_masks: false
  include_yolo_masks: false
  include_hrnet_masks: false # masks are 0 for background, 1, 2, 3... for classes (they look black in file viewer)
  include_unetplusplus_masks: true # very similar to hrnet masks but different structure and no lst files
  mask_threshold_db: 5
  log_scale_masks: true
  include_soundfile: false
  include_spectrogram: true
  length: 10
  lowpass_variable: 100
  n: 1000
  negative_overlay_range:
  - 0
  - 3
  overwrite_output_path: true
  positive_overlay_range:
  - 1
  - 2
  rainbow_frequency: false
  repetitions:
  - 1
  - 4
  single_class: true
  snr_range:
  - 0.05
  - 0.5
  val_ratio: 0.8
  concatenate: false
paths:
  hrnet_remote_dir: '/Users/kaspar/Library/CloudStorage/GoogleDrive-kaspar.kimutai@gmail.com/My Drive/Colab Notebooks/HRNet-Semantic-Segmentation/data' # this path is overwritten
  dataset: example_dataset
  do_train_val_split: false
  negative: vocalisations_xc
  noise: noise
  output: augmented_dataset_output # this path is overwritten every time main.py runs
  vocalisations: test_localisation_vocalisation
plot:
  color_filter: dusk
  toggle: false
  show_labels: true